package org.javautil.dblogging.dto;
// Generated Sep 10, 2011 1:41:31 PM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * UtProcessStat generated by hbm2java
 */
public class UtProcessStat  implements java.io.Serializable {


     private UtProcessStatId id;
     private UtProcessLog utProcessLog;
     private Integer sid;
     private BigDecimal value;

    public UtProcessStat() {
    }

	
    public UtProcessStat(UtProcessStatId id, UtProcessLog utProcessLog) {
        this.id = id;
        this.utProcessLog = utProcessLog;
    }
    public UtProcessStat(UtProcessStatId id, UtProcessLog utProcessLog, Integer sid, BigDecimal value) {
       this.id = id;
       this.utProcessLog = utProcessLog;
       this.sid = sid;
       this.value = value;
    }
   
    public UtProcessStatId getId() {
        return this.id;
    }
    
    public void setId(UtProcessStatId id) {
        this.id = id;
    }
    public UtProcessLog getUtProcessLog() {
        return this.utProcessLog;
    }
    
    public void setUtProcessLog(UtProcessLog utProcessLog) {
        this.utProcessLog = utProcessLog;
    }
    public Integer getSid() {
        return this.sid;
    }
    
    public void setSid(Integer sid) {
        this.sid = sid;
    }
    public BigDecimal getValue() {
        return this.value;
    }
    
    public void setValue(BigDecimal value) {
        this.value = value;
    }




}


