package org.javautil.dblogging.dto;
// Generated Sep 10, 2011 1:41:31 PM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UtProcessStatus generated by hbm2java
 */
public class UtProcessStatus  implements java.io.Serializable {


     private Integer utProcessStatusNbr;
     private String schemaNm;
     private String processNm;
     private String threadNm;
     private Integer processRunNbr;
     private String statusMsg;
     private String statusId;
     private Date statusTs;
     private BigDecimal totalElapsedSeconds;
     private Integer sid;
     private Integer serialNbr;
     private String ignoreFlg;
     private Set<UtProcessLog> utProcessLogs = new HashSet<UtProcessLog>(0);

    public UtProcessStatus() {
    }

    public UtProcessStatus(String schemaNm, String processNm, String threadNm, Integer processRunNbr, String statusMsg, String statusId, Date statusTs, BigDecimal totalElapsedSeconds, Integer sid, Integer serialNbr, String ignoreFlg, Set<UtProcessLog> utProcessLogs) {
       this.schemaNm = schemaNm;
       this.processNm = processNm;
       this.threadNm = threadNm;
       this.processRunNbr = processRunNbr;
       this.statusMsg = statusMsg;
       this.statusId = statusId;
       this.statusTs = statusTs;
       this.totalElapsedSeconds = totalElapsedSeconds;
       this.sid = sid;
       this.serialNbr = serialNbr;
       this.ignoreFlg = ignoreFlg;
       this.utProcessLogs = utProcessLogs;
    }
   
    public Integer getUtProcessStatusNbr() {
        return this.utProcessStatusNbr;
    }
    
    public void setUtProcessStatusNbr(Integer utProcessStatusNbr) {
        this.utProcessStatusNbr = utProcessStatusNbr;
    }
    public String getSchemaNm() {
        return this.schemaNm;
    }
    
    public void setSchemaNm(String schemaNm) {
        this.schemaNm = schemaNm;
    }
    public String getProcessNm() {
        return this.processNm;
    }
    
    public void setProcessNm(String processNm) {
        this.processNm = processNm;
    }
    public String getThreadNm() {
        return this.threadNm;
    }
    
    public void setThreadNm(String threadNm) {
        this.threadNm = threadNm;
    }
    public Integer getProcessRunNbr() {
        return this.processRunNbr;
    }
    
    public void setProcessRunNbr(Integer processRunNbr) {
        this.processRunNbr = processRunNbr;
    }
    public String getStatusMsg() {
        return this.statusMsg;
    }
    
    public void setStatusMsg(String statusMsg) {
        this.statusMsg = statusMsg;
    }
    public String getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(String statusId) {
        this.statusId = statusId;
    }
    public Date getStatusTs() {
        return this.statusTs;
    }
    
    public void setStatusTs(Date statusTs) {
        this.statusTs = statusTs;
    }
    public BigDecimal getTotalElapsedSeconds() {
        return this.totalElapsedSeconds;
    }
    
    public void setTotalElapsedSeconds(BigDecimal totalElapsedSeconds) {
        this.totalElapsedSeconds = totalElapsedSeconds;
    }
    public Integer getSid() {
        return this.sid;
    }
    
    public void setSid(Integer sid) {
        this.sid = sid;
    }
    public Integer getSerialNbr() {
        return this.serialNbr;
    }
    
    public void setSerialNbr(Integer serialNbr) {
        this.serialNbr = serialNbr;
    }
    public String getIgnoreFlg() {
        return this.ignoreFlg;
    }
    
    public void setIgnoreFlg(String ignoreFlg) {
        this.ignoreFlg = ignoreFlg;
    }
    public Set<UtProcessLog> getUtProcessLogs() {
        return this.utProcessLogs;
    }
    
    public void setUtProcessLogs(Set<UtProcessLog> utProcessLogs) {
        this.utProcessLogs = utProcessLogs;
    }




}


