package org.javautil.dblogging.dto;
// Generated Sep 10, 2011 1:41:31 PM by Hibernate Tools 3.2.2.GA



/**
 * UtProcessLogId generated by hbm2java
 */
public class UtProcessLogId  implements java.io.Serializable {


     private int utProcessStatusNbr;
     private long logSeqNbr;

    public UtProcessLogId() {
    }

    public UtProcessLogId(int utProcessStatusNbr, long logSeqNbr) {
       this.utProcessStatusNbr = utProcessStatusNbr;
       this.logSeqNbr = logSeqNbr;
    }
   
    public int getUtProcessStatusNbr() {
        return this.utProcessStatusNbr;
    }
    
    public void setUtProcessStatusNbr(int utProcessStatusNbr) {
        this.utProcessStatusNbr = utProcessStatusNbr;
    }
    public long getLogSeqNbr() {
        return this.logSeqNbr;
    }
    
    public void setLogSeqNbr(long logSeqNbr) {
        this.logSeqNbr = logSeqNbr;
    }




}


