set echo on 
spool service_request_tables

  drop sequence service_rqst_log_nbr_seq;
  drop TABLE SERVICE_RQST;
  drop TABLE SERVICE_RQST_LOG ;
  drop TABLE SERVICE_RQST_PARMS ;

 

 
  create sequence service_rqst_log_nbr_seq;

  CREATE TABLE SERVICE_RQST 
   (	SERVICE_RQST_CD 	VARCHAR2(20) NOT NULL ENABLE, 
	SERVICE_RQST_DESCR 	VARCHAR2(60) NOT NULL ENABLE, 
	CLASSNAME 		VARCHAR2(255), 
	PIPE_NM 		VARCHAR2(255), 
	VALIDATE_FLG 		VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE
   ) ;

  ALTER TABLE SERVICE_RQST ADD 
  CONSTRAINT SERVICE_RQST_PK PRIMARY KEY (SERVICE_RQST_CD) ENABLE;

  ALTER TABLE SERVICE_RQST ADD CHECK (validate_flg in ('Y', 'N')) ENABLE;


  CREATE TABLE SERVICE_RQST_LOG 
   (	SERVICE_RQST_LOG_NBR NUMBER(9,0) NOT NULL ENABLE, 
	SERVICE_RQST_CD VARCHAR2(20) NOT NULL ENABLE, 
	SERVICE_RQST_PARMS VARCHAR2(2048) NOT NULL ENABLE, 
	SERVICE_RQST_ISSUE_TM DATE NOT NULL ENABLE, 
	SERVICE_RQST_COMPLETE_TM DATE, 
	SERVICE_RQST_ELAPSED_MS NUMBER(9,0), 
	SERVICE_RQST_TRACE VARCHAR2(4000), 
	SERVICE_RQST_STAT_ID VARCHAR2(1) NOT NULL ENABLE
   ) ;

  ALTER TABLE SERVICE_RQST_LOG 
  ADD CONSTRAINT SERVICE_RQST_LOG_PK PRIMARY KEY (SERVICE_RQST_LOG_NBR)
  ENABLE;



  CREATE INDEX SERVICE_RQST_LOG_NDX_01 ON SERVICE_RQST_LOG (SERVICE_RQST_CD) ;


  CREATE TABLE SERVICE_RQST_PARMS 
   (	SERVICE_RQST_CD VARCHAR2(20) NOT NULL ENABLE, 
	PARM_NM VARCHAR2(30) NOT NULL ENABLE, 
	PARM_DATA_TYPE VARCHAR2(10) NOT NULL ENABLE, 
	PARM_NM_DESCR VARCHAR2(60) NOT NULL ENABLE
   ) ;

  ALTER TABLE SERVICE_RQST_PARMS ADD CONSTRAINT 
	SERVICE_RQST_PARMS_PK PRIMARY KEY (SERVICE_RQST_CD, PARM_NM)
  ENABLE;

  ALTER TABLE SERVICE_RQST_PARMS ADD CONSTRAINT SRP_SR_FK FOREIGN KEY (SERVICE_RQST_CD)
	  REFERENCES SERVICE_RQST (SERVICE_RQST_CD) ENABLE;
 

 
