package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name="customer"
)
public class Customer  implements java.io.Serializable {


     private int customerId;
     private Org org;

    public Customer() {
    }

    public Customer(int customerId, Org org) {
       this.customerId = customerId;
       this.org = org;
    }
   
     @Id 
    
    @Column(name="customer_id", unique=true, nullable=false)
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id", unique=true, nullable=false, insertable=false, updatable=false)
    public Org getOrg() {
        return this.org;
    }
    
    public void setOrg(Org org) {
        this.org = org;
    }




}


