package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DistributorCustomer generated by hbm2java
 */
@Entity
@Table(name="distributor_customer"
    , uniqueConstraints = @UniqueConstraint(columnNames={"org_distrib_id", "ship_to_cust_id"}) 
)
public class DistributorCustomer  implements java.io.Serializable {


     private int distributorCustomerId;
     private OrgDistrib orgDistrib;
     private String shipToCustId;
     private Set<EtlSale> etlSales = new HashSet<EtlSale>(0);
     private Set<PostSale> postSales = new HashSet<PostSale>(0);

    public DistributorCustomer() {
    }

	
    public DistributorCustomer(int distributorCustomerId, OrgDistrib orgDistrib) {
        this.distributorCustomerId = distributorCustomerId;
        this.orgDistrib = orgDistrib;
    }
    public DistributorCustomer(int distributorCustomerId, OrgDistrib orgDistrib, String shipToCustId, Set<EtlSale> etlSales, Set<PostSale> postSales) {
       this.distributorCustomerId = distributorCustomerId;
       this.orgDistrib = orgDistrib;
       this.shipToCustId = shipToCustId;
       this.etlSales = etlSales;
       this.postSales = postSales;
    }
   
     @Id 
    
    @Column(name="distributor_customer_id", unique=true, nullable=false)
    public int getDistributorCustomerId() {
        return this.distributorCustomerId;
    }
    
    public void setDistributorCustomerId(int distributorCustomerId) {
        this.distributorCustomerId = distributorCustomerId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="org_distrib_id", nullable=false)
    public OrgDistrib getOrgDistrib() {
        return this.orgDistrib;
    }
    
    public void setOrgDistrib(OrgDistrib orgDistrib) {
        this.orgDistrib = orgDistrib;
    }
    
    @Column(name="ship_to_cust_id", length=10)
    public String getShipToCustId() {
        return this.shipToCustId;
    }
    
    public void setShipToCustId(String shipToCustId) {
        this.shipToCustId = shipToCustId;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="distributorCustomer")
    public Set<EtlSale> getEtlSales() {
        return this.etlSales;
    }
    
    public void setEtlSales(Set<EtlSale> etlSales) {
        this.etlSales = etlSales;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="distributorCustomer")
    public Set<PostSale> getPostSales() {
        return this.postSales;
    }
    
    public void setPostSales(Set<PostSale> postSales) {
        this.postSales = postSales;
    }




}


