package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EtlCustomerTot generated by hbm2java
 */
@Entity
@Table(name="etl_customer_tot"
)
public class EtlCustomerTot  implements java.io.Serializable {


     private int etlFileId;
     private EtlFile etlFile;
     private int lineNumber;
     private int customerCount;

    public EtlCustomerTot() {
    }

    public EtlCustomerTot(int etlFileId, EtlFile etlFile, int lineNumber, int customerCount) {
       this.etlFileId = etlFileId;
       this.etlFile = etlFile;
       this.lineNumber = lineNumber;
       this.customerCount = customerCount;
    }
   
     @Id 
    
    @Column(name="etl_file_id", unique=true, nullable=false)
    public int getEtlFileId() {
        return this.etlFileId;
    }
    
    public void setEtlFileId(int etlFileId) {
        this.etlFileId = etlFileId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="etl_file_id", unique=true, nullable=false, insertable=false, updatable=false)
    public EtlFile getEtlFile() {
        return this.etlFile;
    }
    
    public void setEtlFile(EtlFile etlFile) {
        this.etlFile = etlFile;
    }
    
    @Column(name="line_number", nullable=false)
    public int getLineNumber() {
        return this.lineNumber;
    }
    
    public void setLineNumber(int lineNumber) {
        this.lineNumber = lineNumber;
    }
    
    @Column(name="customer_count", nullable=false, precision=9, scale=0)
    public int getCustomerCount() {
        return this.customerCount;
    }
    
    public void setCustomerCount(int customerCount) {
        this.customerCount = customerCount;
    }




}


