package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EtlCustomer generated by hbm2java
 */
@Entity
@Table(name="etl_customer"
)
public class EtlCustomer  implements java.io.Serializable {


     private int etlCustomerId;
     private EtlFile etlFile;
     private String shipToCustId;
     private int lineNumber;
     private String classOfTrade;
     private String custNm;
     private String addr1;
     private String addr2;
     private String city;
     private String state;
     private String postalCd;
     private String cntryId;
     private String telNbr;
     private String nationalAcctId;
     private String specialFlg;
     private Set<CustomerInfo> customerInfos = new HashSet<CustomerInfo>(0);

    public EtlCustomer() {
    }

	
    public EtlCustomer(int etlCustomerId, EtlFile etlFile, String shipToCustId, int lineNumber) {
        this.etlCustomerId = etlCustomerId;
        this.etlFile = etlFile;
        this.shipToCustId = shipToCustId;
        this.lineNumber = lineNumber;
    }
    public EtlCustomer(int etlCustomerId, EtlFile etlFile, String shipToCustId, int lineNumber, String classOfTrade, String custNm, String addr1, String addr2, String city, String state, String postalCd, String cntryId, String telNbr, String nationalAcctId, String specialFlg, Set<CustomerInfo> customerInfos) {
       this.etlCustomerId = etlCustomerId;
       this.etlFile = etlFile;
       this.shipToCustId = shipToCustId;
       this.lineNumber = lineNumber;
       this.classOfTrade = classOfTrade;
       this.custNm = custNm;
       this.addr1 = addr1;
       this.addr2 = addr2;
       this.city = city;
       this.state = state;
       this.postalCd = postalCd;
       this.cntryId = cntryId;
       this.telNbr = telNbr;
       this.nationalAcctId = nationalAcctId;
       this.specialFlg = specialFlg;
       this.customerInfos = customerInfos;
    }
   
     @Id 
    
    @Column(name="etl_customer_id", unique=true, nullable=false)
    public int getEtlCustomerId() {
        return this.etlCustomerId;
    }
    
    public void setEtlCustomerId(int etlCustomerId) {
        this.etlCustomerId = etlCustomerId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="etl_file_id", nullable=false)
    public EtlFile getEtlFile() {
        return this.etlFile;
    }
    
    public void setEtlFile(EtlFile etlFile) {
        this.etlFile = etlFile;
    }
    
    @Column(name="ship_to_cust_id", nullable=false, length=10)
    public String getShipToCustId() {
        return this.shipToCustId;
    }
    
    public void setShipToCustId(String shipToCustId) {
        this.shipToCustId = shipToCustId;
    }
    
    @Column(name="line_number", nullable=false)
    public int getLineNumber() {
        return this.lineNumber;
    }
    
    public void setLineNumber(int lineNumber) {
        this.lineNumber = lineNumber;
    }
    
    @Column(name="class_of_trade", length=4)
    public String getClassOfTrade() {
        return this.classOfTrade;
    }
    
    public void setClassOfTrade(String classOfTrade) {
        this.classOfTrade = classOfTrade;
    }
    
    @Column(name="cust_nm", length=30)
    public String getCustNm() {
        return this.custNm;
    }
    
    public void setCustNm(String custNm) {
        this.custNm = custNm;
    }
    
    @Column(name="addr_1", length=30)
    public String getAddr1() {
        return this.addr1;
    }
    
    public void setAddr1(String addr1) {
        this.addr1 = addr1;
    }
    
    @Column(name="addr_2", length=30)
    public String getAddr2() {
        return this.addr2;
    }
    
    public void setAddr2(String addr2) {
        this.addr2 = addr2;
    }
    
    @Column(name="city", length=25)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    
    @Column(name="state", length=2)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    
    @Column(name="postal_cd", length=9)
    public String getPostalCd() {
        return this.postalCd;
    }
    
    public void setPostalCd(String postalCd) {
        this.postalCd = postalCd;
    }
    
    @Column(name="cntry_id", length=3)
    public String getCntryId() {
        return this.cntryId;
    }
    
    public void setCntryId(String cntryId) {
        this.cntryId = cntryId;
    }
    
    @Column(name="tel_nbr", length=10)
    public String getTelNbr() {
        return this.telNbr;
    }
    
    public void setTelNbr(String telNbr) {
        this.telNbr = telNbr;
    }
    
    @Column(name="national_acct_id", length=10)
    public String getNationalAcctId() {
        return this.nationalAcctId;
    }
    
    public void setNationalAcctId(String nationalAcctId) {
        this.nationalAcctId = nationalAcctId;
    }
    
    @Column(name="special_flg", length=1)
    public String getSpecialFlg() {
        return this.specialFlg;
    }
    
    public void setSpecialFlg(String specialFlg) {
        this.specialFlg = specialFlg;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="etlCustomer")
    public Set<CustomerInfo> getCustomerInfos() {
        return this.customerInfos;
    }
    
    public void setCustomerInfos(Set<CustomerInfo> customerInfos) {
        this.customerInfos = customerInfos;
    }




}


