package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EtlCustomerStatId generated by hbm2java
 */
@Embeddable
public class EtlCustomerStatId  implements java.io.Serializable {


     private Integer etlFileId;
     private Long etlCustomerCount;

    public EtlCustomerStatId() {
    }

    public EtlCustomerStatId(Integer etlFileId, Long etlCustomerCount) {
       this.etlFileId = etlFileId;
       this.etlCustomerCount = etlCustomerCount;
    }
   

    @Column(name="etl_file_id")
    public Integer getEtlFileId() {
        return this.etlFileId;
    }
    
    public void setEtlFileId(Integer etlFileId) {
        this.etlFileId = etlFileId;
    }

    @Column(name="etl_customer_count")
    public Long getEtlCustomerCount() {
        return this.etlCustomerCount;
    }
    
    public void setEtlCustomerCount(Long etlCustomerCount) {
        this.etlCustomerCount = etlCustomerCount;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EtlCustomerStatId) ) return false;
		 EtlCustomerStatId castOther = ( EtlCustomerStatId ) other; 
         
		 return ( (this.getEtlFileId()==castOther.getEtlFileId()) || ( this.getEtlFileId()!=null && castOther.getEtlFileId()!=null && this.getEtlFileId().equals(castOther.getEtlFileId()) ) )
 && ( (this.getEtlCustomerCount()==castOther.getEtlCustomerCount()) || ( this.getEtlCustomerCount()!=null && castOther.getEtlCustomerCount()!=null && this.getEtlCustomerCount().equals(castOther.getEtlCustomerCount()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEtlFileId() == null ? 0 : this.getEtlFileId().hashCode() );
         result = 37 * result + ( getEtlCustomerCount() == null ? 0 : this.getEtlCustomerCount().hashCode() );
         return result;
   }   


}


