package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EtlFile generated by hbm2java
 */
@Entity
@Table(name="etl_file")
public class EtlFile implements java.io.Serializable {


     private int etlFileId;
     private OrgDatafeed orgDatafeed;
     private int datafeedOrgId;
     private Set<EtlCustomerTot> etlCustomerTots = new HashSet<EtlCustomerTot>(0);
     private Set<EtlInventoryTot> etlInventoryTots = new HashSet<EtlInventoryTot>(0);
     private Set<EtlSale> etlSales = new HashSet<EtlSale>(0);
     private Set<EtlSaleTot> etlSaleTots = new HashSet<EtlSaleTot>(0);
     private Set<EtlInventory> etlInventories = new HashSet<EtlInventory>(0);
     private Set<EtlCustomer> etlCustomers = new HashSet<EtlCustomer>(0);

    public EtlFile() {
    }

	
    public EtlFile(int etlFileId, OrgDatafeed orgDatafeed, int datafeedOrgId) {
        this.etlFileId = etlFileId;
        this.orgDatafeed = orgDatafeed;
        this.datafeedOrgId = datafeedOrgId;
    }
    public EtlFile(int etlFileId, OrgDatafeed orgDatafeed, int datafeedOrgId, Set<EtlCustomerTot> etlCustomerTots, Set<EtlInventoryTot> etlInventoryTots, Set<EtlSale> etlSales, Set<EtlSaleTot> etlSaleTots, Set<EtlInventory> etlInventories, Set<EtlCustomer> etlCustomers) {
       this.etlFileId = etlFileId;
       this.orgDatafeed = orgDatafeed;
       this.datafeedOrgId = datafeedOrgId;
       this.etlCustomerTots = etlCustomerTots;
       this.etlInventoryTots = etlInventoryTots;
       this.etlSales = etlSales;
       this.etlSaleTots = etlSaleTots;
       this.etlInventories = etlInventories;
       this.etlCustomers = etlCustomers;
    }
   
     @Id 
    
    @Column(name="etl_file_id", unique=true, nullable=false)
    public int getEtlFileId() {
        return this.etlFileId;
    }
    
    public void setEtlFileId(int etlFileId) {
        this.etlFileId = etlFileId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rpt_org_id", nullable=false)
    public OrgDatafeed getOrgDatafeed() {
        return this.orgDatafeed;
    }
    
    public void setOrgDatafeed(OrgDatafeed orgDatafeed) {
        this.orgDatafeed = orgDatafeed;
    }
    
    @Column(name="datafeed_org_id", nullable=false)
    public int getDatafeedOrgId() {
        return this.datafeedOrgId;
    }
    
    public void setDatafeedOrgId(int datafeedOrgId) {
        this.datafeedOrgId = datafeedOrgId;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="etlFile")
    public Set<EtlCustomerTot> getEtlCustomerTots() {
        return this.etlCustomerTots;
    }
    
    public void setEtlCustomerTots(Set<EtlCustomerTot> etlCustomerTots) {
        this.etlCustomerTots = etlCustomerTots;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="etlFile")
    public Set<EtlInventoryTot> getEtlInventoryTots() {
        return this.etlInventoryTots;
    }
    
    public void setEtlInventoryTots(Set<EtlInventoryTot> etlInventoryTots) {
        this.etlInventoryTots = etlInventoryTots;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="etlFile")
    public Set<EtlSale> getEtlSales() {
        return this.etlSales;
    }
    
    public void setEtlSales(Set<EtlSale> etlSales) {
        this.etlSales = etlSales;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="etlFile")
    public Set<EtlSaleTot> getEtlSaleTots() {
        return this.etlSaleTots;
    }
    
    public void setEtlSaleTots(Set<EtlSaleTot> etlSaleTots) {
        this.etlSaleTots = etlSaleTots;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="etlFile")
    public Set<EtlInventory> getEtlInventories() {
        return this.etlInventories;
    }
    
    public void setEtlInventories(Set<EtlInventory> etlInventories) {
        this.etlInventories = etlInventories;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="etlFile")
    public Set<EtlCustomer> getEtlCustomers() {
        return this.etlCustomers;
    }
    
    public void setEtlCustomers(Set<EtlCustomer> etlCustomers) {
        this.etlCustomers = etlCustomers;
    }




}


