package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EtlFileStatId generated by hbm2java
 */
@Embeddable
public class EtlFileStatId  implements java.io.Serializable {


     private Integer etlFileId;
     private Integer datafeedOrgId;
     private Long etlCustomerCount;
     private Long etlSaleCount;
     private Date invoiceDtMin;
     private Date invoiceDtMax;

    public EtlFileStatId() {
    }

    public EtlFileStatId(Integer etlFileId, Integer datafeedOrgId, Long etlCustomerCount, Long etlSaleCount, Date invoiceDtMin, Date invoiceDtMax) {
       this.etlFileId = etlFileId;
       this.datafeedOrgId = datafeedOrgId;
       this.etlCustomerCount = etlCustomerCount;
       this.etlSaleCount = etlSaleCount;
       this.invoiceDtMin = invoiceDtMin;
       this.invoiceDtMax = invoiceDtMax;
    }
   

    @Column(name="etl_file_id")
    public Integer getEtlFileId() {
        return this.etlFileId;
    }
    
    public void setEtlFileId(Integer etlFileId) {
        this.etlFileId = etlFileId;
    }

    @Column(name="datafeed_org_id")
    public Integer getDatafeedOrgId() {
        return this.datafeedOrgId;
    }
    
    public void setDatafeedOrgId(Integer datafeedOrgId) {
        this.datafeedOrgId = datafeedOrgId;
    }

    @Column(name="etl_customer_count")
    public Long getEtlCustomerCount() {
        return this.etlCustomerCount;
    }
    
    public void setEtlCustomerCount(Long etlCustomerCount) {
        this.etlCustomerCount = etlCustomerCount;
    }

    @Column(name="etl_sale_count")
    public Long getEtlSaleCount() {
        return this.etlSaleCount;
    }
    
    public void setEtlSaleCount(Long etlSaleCount) {
        this.etlSaleCount = etlSaleCount;
    }

    @Column(name="invoice_dt_min", length=13)
    public Date getInvoiceDtMin() {
        return this.invoiceDtMin;
    }
    
    public void setInvoiceDtMin(Date invoiceDtMin) {
        this.invoiceDtMin = invoiceDtMin;
    }

    @Column(name="invoice_dt_max", length=13)
    public Date getInvoiceDtMax() {
        return this.invoiceDtMax;
    }
    
    public void setInvoiceDtMax(Date invoiceDtMax) {
        this.invoiceDtMax = invoiceDtMax;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EtlFileStatId) ) return false;
		 EtlFileStatId castOther = ( EtlFileStatId ) other; 
         
		 return ( (this.getEtlFileId()==castOther.getEtlFileId()) || ( this.getEtlFileId()!=null && castOther.getEtlFileId()!=null && this.getEtlFileId().equals(castOther.getEtlFileId()) ) )
 && ( (this.getDatafeedOrgId()==castOther.getDatafeedOrgId()) || ( this.getDatafeedOrgId()!=null && castOther.getDatafeedOrgId()!=null && this.getDatafeedOrgId().equals(castOther.getDatafeedOrgId()) ) )
 && ( (this.getEtlCustomerCount()==castOther.getEtlCustomerCount()) || ( this.getEtlCustomerCount()!=null && castOther.getEtlCustomerCount()!=null && this.getEtlCustomerCount().equals(castOther.getEtlCustomerCount()) ) )
 && ( (this.getEtlSaleCount()==castOther.getEtlSaleCount()) || ( this.getEtlSaleCount()!=null && castOther.getEtlSaleCount()!=null && this.getEtlSaleCount().equals(castOther.getEtlSaleCount()) ) )
 && ( (this.getInvoiceDtMin()==castOther.getInvoiceDtMin()) || ( this.getInvoiceDtMin()!=null && castOther.getInvoiceDtMin()!=null && this.getInvoiceDtMin().equals(castOther.getInvoiceDtMin()) ) )
 && ( (this.getInvoiceDtMax()==castOther.getInvoiceDtMax()) || ( this.getInvoiceDtMax()!=null && castOther.getInvoiceDtMax()!=null && this.getInvoiceDtMax().equals(castOther.getInvoiceDtMax()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEtlFileId() == null ? 0 : this.getEtlFileId().hashCode() );
         result = 37 * result + ( getDatafeedOrgId() == null ? 0 : this.getDatafeedOrgId().hashCode() );
         result = 37 * result + ( getEtlCustomerCount() == null ? 0 : this.getEtlCustomerCount().hashCode() );
         result = 37 * result + ( getEtlSaleCount() == null ? 0 : this.getEtlSaleCount().hashCode() );
         result = 37 * result + ( getInvoiceDtMin() == null ? 0 : this.getInvoiceDtMin().hashCode() );
         result = 37 * result + ( getInvoiceDtMax() == null ? 0 : this.getInvoiceDtMax().hashCode() );
         return result;
   }   


}


