package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EtlFileStat generated by hbm2java
 */
@Entity
@Table(name="etl_file_stat"
)
public class EtlFileStat  implements java.io.Serializable {


     private EtlFileStatId id;

    public EtlFileStat() {
    }

    public EtlFileStat(EtlFileStatId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="etlFileId", column=@Column(name="etl_file_id") ), 
        @AttributeOverride(name="datafeedOrgId", column=@Column(name="datafeed_org_id") ), 
        @AttributeOverride(name="etlCustomerCount", column=@Column(name="etl_customer_count") ), 
        @AttributeOverride(name="etlSaleCount", column=@Column(name="etl_sale_count") ), 
        @AttributeOverride(name="invoiceDtMin", column=@Column(name="invoice_dt_min", length=13) ), 
        @AttributeOverride(name="invoiceDtMax", column=@Column(name="invoice_dt_max", length=13) ) } )
    public EtlFileStatId getId() {
        return this.id;
    }
    
    public void setId(EtlFileStatId id) {
        this.id = id;
    }




}


