package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EtlInventory generated by hbm2java
 */
@Entity
@Table(name="etl_inventory"
)
public class EtlInventory  implements java.io.Serializable {


     private int etlInventoryId;
     private EtlFile etlFile;
     private Integer lineNumber;
     private String distributorId;
     private String mfrId;
     private String mfrProductId;
     private String comments;
     private Integer cases;
     private Integer boxes;
     private Integer units;
     private String caseGtin;
     private BigDecimal inventoryQty;
     private String inventoryUnitMeasId;

    public EtlInventory() {
    }

	
    public EtlInventory(int etlInventoryId, EtlFile etlFile) {
        this.etlInventoryId = etlInventoryId;
        this.etlFile = etlFile;
    }
    public EtlInventory(int etlInventoryId, EtlFile etlFile, Integer lineNumber, String distributorId, String mfrId, String mfrProductId, String comments, Integer cases, Integer boxes, Integer units, String caseGtin, BigDecimal inventoryQty, String inventoryUnitMeasId) {
       this.etlInventoryId = etlInventoryId;
       this.etlFile = etlFile;
       this.lineNumber = lineNumber;
       this.distributorId = distributorId;
       this.mfrId = mfrId;
       this.mfrProductId = mfrProductId;
       this.comments = comments;
       this.cases = cases;
       this.boxes = boxes;
       this.units = units;
       this.caseGtin = caseGtin;
       this.inventoryQty = inventoryQty;
       this.inventoryUnitMeasId = inventoryUnitMeasId;
    }
   
     @Id 
    
    @Column(name="etl_inventory_id", unique=true, nullable=false)
    public int getEtlInventoryId() {
        return this.etlInventoryId;
    }
    
    public void setEtlInventoryId(int etlInventoryId) {
        this.etlInventoryId = etlInventoryId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="etl_file_id", nullable=false)
    public EtlFile getEtlFile() {
        return this.etlFile;
    }
    
    public void setEtlFile(EtlFile etlFile) {
        this.etlFile = etlFile;
    }
    
    @Column(name="line_number")
    public Integer getLineNumber() {
        return this.lineNumber;
    }
    
    public void setLineNumber(Integer lineNumber) {
        this.lineNumber = lineNumber;
    }
    
    @Column(name="distributor_id", length=10)
    public String getDistributorId() {
        return this.distributorId;
    }
    
    public void setDistributorId(String distributorId) {
        this.distributorId = distributorId;
    }
    
    @Column(name="mfr_id", length=10)
    public String getMfrId() {
        return this.mfrId;
    }
    
    public void setMfrId(String mfrId) {
        this.mfrId = mfrId;
    }
    
    @Column(name="mfr_product_id", length=8)
    public String getMfrProductId() {
        return this.mfrProductId;
    }
    
    public void setMfrProductId(String mfrProductId) {
        this.mfrProductId = mfrProductId;
    }
    
    @Column(name="comments", length=96)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    
    @Column(name="cases", precision=6, scale=0)
    public Integer getCases() {
        return this.cases;
    }
    
    public void setCases(Integer cases) {
        this.cases = cases;
    }
    
    @Column(name="boxes", precision=6, scale=0)
    public Integer getBoxes() {
        return this.boxes;
    }
    
    public void setBoxes(Integer boxes) {
        this.boxes = boxes;
    }
    
    @Column(name="units", precision=6, scale=0)
    public Integer getUnits() {
        return this.units;
    }
    
    public void setUnits(Integer units) {
        this.units = units;
    }
    
    @Column(name="case_gtin", length=14)
    public String getCaseGtin() {
        return this.caseGtin;
    }
    
    public void setCaseGtin(String caseGtin) {
        this.caseGtin = caseGtin;
    }
    
    @Column(name="inventory_qty", precision=9, scale=3)
    public BigDecimal getInventoryQty() {
        return this.inventoryQty;
    }
    
    public void setInventoryQty(BigDecimal inventoryQty) {
        this.inventoryQty = inventoryQty;
    }
    
    @Column(name="inventory_unit_meas_id", length=3)
    public String getInventoryUnitMeasId() {
        return this.inventoryUnitMeasId;
    }
    
    public void setInventoryUnitMeasId(String inventoryUnitMeasId) {
        this.inventoryUnitMeasId = inventoryUnitMeasId;
    }




}


