package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EtlSaleUnknownItemId generated by hbm2java
 */
@Embeddable
public class EtlSaleUnknownItemId  implements java.io.Serializable {


     private String productDescr;
     private String distribId;
     private BigDecimal extendedNetAmtSum;
     private String distribProductRef;
     private String caseGtin;

    public EtlSaleUnknownItemId() {
    }

    public EtlSaleUnknownItemId(String productDescr, String distribId, BigDecimal extendedNetAmtSum, String distribProductRef, String caseGtin) {
       this.productDescr = productDescr;
       this.distribId = distribId;
       this.extendedNetAmtSum = extendedNetAmtSum;
       this.distribProductRef = distribProductRef;
       this.caseGtin = caseGtin;
    }
   

    @Column(name="product_descr", length=32)
    public String getProductDescr() {
        return this.productDescr;
    }
    
    public void setProductDescr(String productDescr) {
        this.productDescr = productDescr;
    }

    @Column(name="distrib_id", length=10)
    public String getDistribId() {
        return this.distribId;
    }
    
    public void setDistribId(String distribId) {
        this.distribId = distribId;
    }

    @Column(name="extended_net_amt_sum", precision=131089, scale=0)
    public BigDecimal getExtendedNetAmtSum() {
        return this.extendedNetAmtSum;
    }
    
    public void setExtendedNetAmtSum(BigDecimal extendedNetAmtSum) {
        this.extendedNetAmtSum = extendedNetAmtSum;
    }

    @Column(name="distrib_product_ref", length=12)
    public String getDistribProductRef() {
        return this.distribProductRef;
    }
    
    public void setDistribProductRef(String distribProductRef) {
        this.distribProductRef = distribProductRef;
    }

    @Column(name="case_gtin", length=14)
    public String getCaseGtin() {
        return this.caseGtin;
    }
    
    public void setCaseGtin(String caseGtin) {
        this.caseGtin = caseGtin;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EtlSaleUnknownItemId) ) return false;
		 EtlSaleUnknownItemId castOther = ( EtlSaleUnknownItemId ) other; 
         
		 return ( (this.getProductDescr()==castOther.getProductDescr()) || ( this.getProductDescr()!=null && castOther.getProductDescr()!=null && this.getProductDescr().equals(castOther.getProductDescr()) ) )
 && ( (this.getDistribId()==castOther.getDistribId()) || ( this.getDistribId()!=null && castOther.getDistribId()!=null && this.getDistribId().equals(castOther.getDistribId()) ) )
 && ( (this.getExtendedNetAmtSum()==castOther.getExtendedNetAmtSum()) || ( this.getExtendedNetAmtSum()!=null && castOther.getExtendedNetAmtSum()!=null && this.getExtendedNetAmtSum().equals(castOther.getExtendedNetAmtSum()) ) )
 && ( (this.getDistribProductRef()==castOther.getDistribProductRef()) || ( this.getDistribProductRef()!=null && castOther.getDistribProductRef()!=null && this.getDistribProductRef().equals(castOther.getDistribProductRef()) ) )
 && ( (this.getCaseGtin()==castOther.getCaseGtin()) || ( this.getCaseGtin()!=null && castOther.getCaseGtin()!=null && this.getCaseGtin().equals(castOther.getCaseGtin()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProductDescr() == null ? 0 : this.getProductDescr().hashCode() );
         result = 37 * result + ( getDistribId() == null ? 0 : this.getDistribId().hashCode() );
         result = 37 * result + ( getExtendedNetAmtSum() == null ? 0 : this.getExtendedNetAmtSum().hashCode() );
         result = 37 * result + ( getDistribProductRef() == null ? 0 : this.getDistribProductRef().hashCode() );
         result = 37 * result + ( getCaseGtin() == null ? 0 : this.getCaseGtin().hashCode() );
         return result;
   }   


}


