package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EtlSalePostStats generated by hbm2java
 */
@Entity
@Table(name="etl_sale_post_stats"
)
public class EtlSalePostStats  implements java.io.Serializable {


     private EtlSalePostStatsId id;

    public EtlSalePostStats() {
    }

    public EtlSalePostStats(EtlSalePostStatsId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="etlFileId", column=@Column(name="etl_file_id") ), 
        @AttributeOverride(name="recordCount", column=@Column(name="record_count") ), 
        @AttributeOverride(name="orgDistribIdCount", column=@Column(name="org_distrib_id_count") ), 
        @AttributeOverride(name="orgMfrIdCount", column=@Column(name="org_mfr_id_count") ), 
        @AttributeOverride(name="productIdCount", column=@Column(name="product_id_count") ), 
        @AttributeOverride(name="customerIdCount", column=@Column(name="customer_id_count") ), 
        @AttributeOverride(name="postableCount", column=@Column(name="postable_count") ) } )
    public EtlSalePostStatsId getId() {
        return this.id;
    }
    
    public void setId(EtlSalePostStatsId id) {
        this.id = id;
    }




}


