package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EtlSale generated by hbm2java
 */
@Entity
@Table(name="etl_sale"
)
public class EtlSale  implements java.io.Serializable {


     private int etlSaleId;
     private OrgDistrib orgDistrib;
     private EtlFile etlFile;
     private DistributorCustomer distributorCustomer;
     private Product product;
     private OrgMfr orgMfr;
     private Integer lineNumber;
     private String distribId;
     private String mfrId;
     private String mfrProductId;
     private String shipToCustId;
     private String invoiceCd;
     private Date invoiceDt;
     private Date shipDt;
     private BigDecimal extendedNetAmt;
     private String currCd;
     private String distribProductRef;
     private String productDescr;
     private Integer casesShipped;
     private Integer boxesShipped;
     private Integer unitsShipped;
     private String caseGtin;
     private Set<PostSale> postSales = new HashSet<PostSale>(0);

    public EtlSale() {
    }

	
    public EtlSale(int etlSaleId, EtlFile etlFile, String distribId, String mfrId, String shipToCustId) {
        this.etlSaleId = etlSaleId;
        this.etlFile = etlFile;
        this.distribId = distribId;
        this.mfrId = mfrId;
        this.shipToCustId = shipToCustId;
    }
    public EtlSale(int etlSaleId, OrgDistrib orgDistrib, EtlFile etlFile, DistributorCustomer distributorCustomer, Product product, OrgMfr orgMfr, Integer lineNumber, String distribId, String mfrId, String mfrProductId, String shipToCustId, String invoiceCd, Date invoiceDt, Date shipDt, BigDecimal extendedNetAmt, String currCd, String distribProductRef, String productDescr, Integer casesShipped, Integer boxesShipped, Integer unitsShipped, String caseGtin, Set<PostSale> postSales) {
       this.etlSaleId = etlSaleId;
       this.orgDistrib = orgDistrib;
       this.etlFile = etlFile;
       this.distributorCustomer = distributorCustomer;
       this.product = product;
       this.orgMfr = orgMfr;
       this.lineNumber = lineNumber;
       this.distribId = distribId;
       this.mfrId = mfrId;
       this.mfrProductId = mfrProductId;
       this.shipToCustId = shipToCustId;
       this.invoiceCd = invoiceCd;
       this.invoiceDt = invoiceDt;
       this.shipDt = shipDt;
       this.extendedNetAmt = extendedNetAmt;
       this.currCd = currCd;
       this.distribProductRef = distribProductRef;
       this.productDescr = productDescr;
       this.casesShipped = casesShipped;
       this.boxesShipped = boxesShipped;
       this.unitsShipped = unitsShipped;
       this.caseGtin = caseGtin;
       this.postSales = postSales;
    }
   
     @Id 
    
    @Column(name="etl_sale_id", unique=true, nullable=false)
    public int getEtlSaleId() {
        return this.etlSaleId;
    }
    
    public void setEtlSaleId(int etlSaleId) {
        this.etlSaleId = etlSaleId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="org_distrib_id")
    public OrgDistrib getOrgDistrib() {
        return this.orgDistrib;
    }
    
    public void setOrgDistrib(OrgDistrib orgDistrib) {
        this.orgDistrib = orgDistrib;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="etl_file_id", nullable=false)
    public EtlFile getEtlFile() {
        return this.etlFile;
    }
    
    public void setEtlFile(EtlFile etlFile) {
        this.etlFile = etlFile;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="distributor_customer_id")
    public DistributorCustomer getDistributorCustomer() {
        return this.distributorCustomer;
    }
    
    public void setDistributorCustomer(DistributorCustomer distributorCustomer) {
        this.distributorCustomer = distributorCustomer;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id")
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="org_mfr_id")
    public OrgMfr getOrgMfr() {
        return this.orgMfr;
    }
    
    public void setOrgMfr(OrgMfr orgMfr) {
        this.orgMfr = orgMfr;
    }
    
    @Column(name="line_number")
    public Integer getLineNumber() {
        return this.lineNumber;
    }
    
    public void setLineNumber(Integer lineNumber) {
        this.lineNumber = lineNumber;
    }
    
    @Column(name="distrib_id", nullable=false, length=10)
    public String getDistribId() {
        return this.distribId;
    }
    
    public void setDistribId(String distribId) {
        this.distribId = distribId;
    }
    
    @Column(name="mfr_id", nullable=false, length=10)
    public String getMfrId() {
        return this.mfrId;
    }
    
    public void setMfrId(String mfrId) {
        this.mfrId = mfrId;
    }
    
    @Column(name="mfr_product_id", length=8)
    public String getMfrProductId() {
        return this.mfrProductId;
    }
    
    public void setMfrProductId(String mfrProductId) {
        this.mfrProductId = mfrProductId;
    }
    
    @Column(name="ship_to_cust_id", nullable=false, length=10)
    public String getShipToCustId() {
        return this.shipToCustId;
    }
    
    public void setShipToCustId(String shipToCustId) {
        this.shipToCustId = shipToCustId;
    }
    
    @Column(name="invoice_cd", length=10)
    public String getInvoiceCd() {
        return this.invoiceCd;
    }
    
    public void setInvoiceCd(String invoiceCd) {
        this.invoiceCd = invoiceCd;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="invoice_dt", length=13)
    public Date getInvoiceDt() {
        return this.invoiceDt;
    }
    
    public void setInvoiceDt(Date invoiceDt) {
        this.invoiceDt = invoiceDt;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="ship_dt", length=13)
    public Date getShipDt() {
        return this.shipDt;
    }
    
    public void setShipDt(Date shipDt) {
        this.shipDt = shipDt;
    }
    
    @Column(name="extended_net_amt", precision=9)
    public BigDecimal getExtendedNetAmt() {
        return this.extendedNetAmt;
    }
    
    public void setExtendedNetAmt(BigDecimal extendedNetAmt) {
        this.extendedNetAmt = extendedNetAmt;
    }
    
    @Column(name="curr_cd", length=3)
    public String getCurrCd() {
        return this.currCd;
    }
    
    public void setCurrCd(String currCd) {
        this.currCd = currCd;
    }
    
    @Column(name="distrib_product_ref", length=12)
    public String getDistribProductRef() {
        return this.distribProductRef;
    }
    
    public void setDistribProductRef(String distribProductRef) {
        this.distribProductRef = distribProductRef;
    }
    
    @Column(name="product_descr", length=32)
    public String getProductDescr() {
        return this.productDescr;
    }
    
    public void setProductDescr(String productDescr) {
        this.productDescr = productDescr;
    }
    
    @Column(name="cases_shipped", precision=9, scale=0)
    public Integer getCasesShipped() {
        return this.casesShipped;
    }
    
    public void setCasesShipped(Integer casesShipped) {
        this.casesShipped = casesShipped;
    }
    
    @Column(name="boxes_shipped", precision=9, scale=0)
    public Integer getBoxesShipped() {
        return this.boxesShipped;
    }
    
    public void setBoxesShipped(Integer boxesShipped) {
        this.boxesShipped = boxesShipped;
    }
    
    @Column(name="units_shipped", precision=9, scale=0)
    public Integer getUnitsShipped() {
        return this.unitsShipped;
    }
    
    public void setUnitsShipped(Integer unitsShipped) {
        this.unitsShipped = unitsShipped;
    }
    
    @Column(name="case_gtin", length=14)
    public String getCaseGtin() {
        return this.caseGtin;
    }
    
    public void setCaseGtin(String caseGtin) {
        this.caseGtin = caseGtin;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="etlSale")
    public Set<PostSale> getPostSales() {
        return this.postSales;
    }
    
    public void setPostSales(Set<PostSale> postSales) {
        this.postSales = postSales;
    }




}


