package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EtlSaleStat generated by hbm2java
 */
@Entity
@Table(name="etl_sale_stat"
)
public class EtlSaleStat  implements java.io.Serializable {


     private EtlSaleStatId id;

    public EtlSaleStat() {
    }

    public EtlSaleStat(EtlSaleStatId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="etlFileId", column=@Column(name="etl_file_id") ), 
        @AttributeOverride(name="etlSaleCount", column=@Column(name="etl_sale_count") ), 
        @AttributeOverride(name="invoiceDtMin", column=@Column(name="invoice_dt_min", length=13) ), 
        @AttributeOverride(name="invoiceDtMax", column=@Column(name="invoice_dt_max", length=13) ) } )
    public EtlSaleStatId getId() {
        return this.id;
    }
    
    public void setId(EtlSaleStatId id) {
        this.id = id;
    }




}


