package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EtlSaleUnknownItem generated by hbm2java
 */
@Entity
@Table(name="etl_sale_unknown_item"
)
public class EtlSaleUnknownItem  implements java.io.Serializable {


     private EtlSaleUnknownItemId id;

    public EtlSaleUnknownItem() {
    }

    public EtlSaleUnknownItem(EtlSaleUnknownItemId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="productDescr", column=@Column(name="product_descr", length=32) ), 
        @AttributeOverride(name="distribId", column=@Column(name="distrib_id", length=10) ), 
        @AttributeOverride(name="extendedNetAmtSum", column=@Column(name="extended_net_amt_sum", precision=131089, scale=0) ), 
        @AttributeOverride(name="distribProductRef", column=@Column(name="distrib_product_ref", length=12) ), 
        @AttributeOverride(name="caseGtin", column=@Column(name="case_gtin", length=14) ) } )
    public EtlSaleUnknownItemId getId() {
        return this.id;
    }
    
    public void setId(EtlSaleUnknownItemId id) {
        this.id = id;
    }




}


