package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LoadConditionsId generated by hbm2java
 */
@Embeddable
public class LoadConditionsId  implements java.io.Serializable {


     private BigDecimal etlFileId;
     private String tableName;
     private String conditionName;
     private Long conditionCount;

    public LoadConditionsId() {
    }

    public LoadConditionsId(BigDecimal etlFileId, String tableName, String conditionName, Long conditionCount) {
       this.etlFileId = etlFileId;
       this.tableName = tableName;
       this.conditionName = conditionName;
       this.conditionCount = conditionCount;
    }
   

    @Column(name="etl_file_id", precision=131089, scale=0)
    public BigDecimal getEtlFileId() {
        return this.etlFileId;
    }
    
    public void setEtlFileId(BigDecimal etlFileId) {
        this.etlFileId = etlFileId;
    }

    @Column(name="table_name", length=60)
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    @Column(name="condition_name", length=30)
    public String getConditionName() {
        return this.conditionName;
    }
    
    public void setConditionName(String conditionName) {
        this.conditionName = conditionName;
    }

    @Column(name="condition_count")
    public Long getConditionCount() {
        return this.conditionCount;
    }
    
    public void setConditionCount(Long conditionCount) {
        this.conditionCount = conditionCount;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LoadConditionsId) ) return false;
		 LoadConditionsId castOther = ( LoadConditionsId ) other; 
         
		 return ( (this.getEtlFileId()==castOther.getEtlFileId()) || ( this.getEtlFileId()!=null && castOther.getEtlFileId()!=null && this.getEtlFileId().equals(castOther.getEtlFileId()) ) )
 && ( (this.getTableName()==castOther.getTableName()) || ( this.getTableName()!=null && castOther.getTableName()!=null && this.getTableName().equals(castOther.getTableName()) ) )
 && ( (this.getConditionName()==castOther.getConditionName()) || ( this.getConditionName()!=null && castOther.getConditionName()!=null && this.getConditionName().equals(castOther.getConditionName()) ) )
 && ( (this.getConditionCount()==castOther.getConditionCount()) || ( this.getConditionCount()!=null && castOther.getConditionCount()!=null && this.getConditionCount().equals(castOther.getConditionCount()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEtlFileId() == null ? 0 : this.getEtlFileId().hashCode() );
         result = 37 * result + ( getTableName() == null ? 0 : this.getTableName().hashCode() );
         result = 37 * result + ( getConditionName() == null ? 0 : this.getConditionName().hashCode() );
         result = 37 * result + ( getConditionCount() == null ? 0 : this.getConditionCount().hashCode() );
         return result;
   }   


}


