package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Org generated by hbm2java
 */
@Entity
@Table(name="org"
)
public class Org  implements java.io.Serializable {


     private int orgId;
     private String orgCd;
     private String orgNm;
     private Set<Customer> customers = new HashSet<Customer>(0);
     private Set<OrgCustomer> orgCustomers = new HashSet<OrgCustomer>(0);
     private Set<OrgDistrib> orgDistribs = new HashSet<OrgDistrib>(0);
     private Set<OrgMfr> orgMfrs = new HashSet<OrgMfr>(0);
     private Set<ProductNomen> productNomens = new HashSet<ProductNomen>(0);
     private Set<OrgDatafeed> orgDatafeeds = new HashSet<OrgDatafeed>(0);

    public Org() {
    }

	
    public Org(int orgId) {
        this.orgId = orgId;
    }
    public Org(int orgId, String orgCd, String orgNm, Set<Customer> customers, Set<OrgCustomer> orgCustomers, Set<OrgDistrib> orgDistribs, Set<OrgMfr> orgMfrs, Set<ProductNomen> productNomens, Set<OrgDatafeed> orgDatafeeds) {
       this.orgId = orgId;
       this.orgCd = orgCd;
       this.orgNm = orgNm;
       this.customers = customers;
       this.orgCustomers = orgCustomers;
       this.orgDistribs = orgDistribs;
       this.orgMfrs = orgMfrs;
       this.productNomens = productNomens;
       this.orgDatafeeds = orgDatafeeds;
    }
   
     @Id 
    
    @Column(name="org_id", unique=true, nullable=false)
    public int getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(int orgId) {
        this.orgId = orgId;
    }
    
    @Column(name="org_cd", length=16)
    public String getOrgCd() {
        return this.orgCd;
    }
    
    public void setOrgCd(String orgCd) {
        this.orgCd = orgCd;
    }
    
    @Column(name="org_nm", length=32)
    public String getOrgNm() {
        return this.orgNm;
    }
    
    public void setOrgNm(String orgNm) {
        this.orgNm = orgNm;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="org")
    public Set<Customer> getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set<Customer> customers) {
        this.customers = customers;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="org")
    public Set<OrgCustomer> getOrgCustomers() {
        return this.orgCustomers;
    }
    
    public void setOrgCustomers(Set<OrgCustomer> orgCustomers) {
        this.orgCustomers = orgCustomers;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="org")
    public Set<OrgDistrib> getOrgDistribs() {
        return this.orgDistribs;
    }
    
    public void setOrgDistribs(Set<OrgDistrib> orgDistribs) {
        this.orgDistribs = orgDistribs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="org")
    public Set<OrgMfr> getOrgMfrs() {
        return this.orgMfrs;
    }
    
    public void setOrgMfrs(Set<OrgMfr> orgMfrs) {
        this.orgMfrs = orgMfrs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="org")
    public Set<ProductNomen> getProductNomens() {
        return this.productNomens;
    }
    
    public void setProductNomens(Set<ProductNomen> productNomens) {
        this.productNomens = productNomens;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="org")
    public Set<OrgDatafeed> getOrgDatafeeds() {
        return this.orgDatafeeds;
    }
    
    public void setOrgDatafeeds(Set<OrgDatafeed> orgDatafeeds) {
        this.orgDatafeeds = orgDatafeeds;
    }




}


