package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrgCustomer generated by hbm2java
 */
@Entity
@Table(name="org_customer"
)
public class OrgCustomer  implements java.io.Serializable {


     private int orgId;
     private Org org;

    public OrgCustomer() {
    }

    public OrgCustomer(int orgId, Org org) {
       this.orgId = orgId;
       this.org = org;
    }
   
     @Id 
    
    @Column(name="org_id", unique=true, nullable=false)
    public int getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(int orgId) {
        this.orgId = orgId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="org_id", unique=true, nullable=false, insertable=false, updatable=false)
    public Org getOrg() {
        return this.org;
    }
    
    public void setOrg(Org org) {
        this.org = org;
    }




}


