package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrgDistrib generated by hbm2java
 */
@Entity
@Table(name="org_distrib"
)
public class OrgDistrib  implements java.io.Serializable {


     private int orgId;
     private Org org;
     private String distribId;
     private Set<PostSale> postSales = new HashSet<PostSale>(0);
     private Set<DistributorCustomer> distributorCustomers = new HashSet<DistributorCustomer>(0);
     private Set<EtlSale> etlSales = new HashSet<EtlSale>(0);

    public OrgDistrib() {
    }

	
    public OrgDistrib(int orgId, Org org, String distribId) {
        this.orgId = orgId;
        this.org = org;
        this.distribId = distribId;
    }
    public OrgDistrib(int orgId, Org org, String distribId, Set<PostSale> postSales, Set<DistributorCustomer> distributorCustomers, Set<EtlSale> etlSales) {
       this.orgId = orgId;
       this.org = org;
       this.distribId = distribId;
       this.postSales = postSales;
       this.distributorCustomers = distributorCustomers;
       this.etlSales = etlSales;
    }
   
     @Id 
    
    @Column(name="org_id", unique=true, nullable=false)
    public int getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(int orgId) {
        this.orgId = orgId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="org_id", unique=true, nullable=false, insertable=false, updatable=false)
    public Org getOrg() {
        return this.org;
    }
    
    public void setOrg(Org org) {
        this.org = org;
    }
    
    @Column(name="distrib_id", nullable=false, length=10)
    public String getDistribId() {
        return this.distribId;
    }
    
    public void setDistribId(String distribId) {
        this.distribId = distribId;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="orgDistrib")
    public Set<PostSale> getPostSales() {
        return this.postSales;
    }
    
    public void setPostSales(Set<PostSale> postSales) {
        this.postSales = postSales;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="orgDistrib")
    public Set<DistributorCustomer> getDistributorCustomers() {
        return this.distributorCustomers;
    }
    
    public void setDistributorCustomers(Set<DistributorCustomer> distributorCustomers) {
        this.distributorCustomers = distributorCustomers;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="orgDistrib")
    public Set<EtlSale> getEtlSales() {
        return this.etlSales;
    }
    
    public void setEtlSales(Set<EtlSale> etlSales) {
        this.etlSales = etlSales;
    }




}


