package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrgDatafeed generated by hbm2java
 */
@Entity
@Table(name="org_datafeed"
)
public class OrgDatafeed  implements java.io.Serializable {


     private int orgId;
     private Org org;
     private Set<EtlFile> etlFiles = new HashSet<EtlFile>(0);

    public OrgDatafeed() {
    }

	
    public OrgDatafeed(int orgId, Org org) {
        this.orgId = orgId;
        this.org = org;
    }
    public OrgDatafeed(int orgId, Org org, Set<EtlFile> etlFiles) {
       this.orgId = orgId;
       this.org = org;
       this.etlFiles = etlFiles;
    }
   
     @Id 
    
    @Column(name="org_id", unique=true, nullable=false)
    public int getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(int orgId) {
        this.orgId = orgId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="org_id", unique=true, nullable=false, insertable=false, updatable=false)
    public Org getOrg() {
        return this.org;
    }
    
    public void setOrg(Org org) {
        this.org = org;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="orgDatafeed")
    public Set<EtlFile> getEtlFiles() {
        return this.etlFiles;
    }
    
    public void setEtlFiles(Set<EtlFile> etlFiles) {
        this.etlFiles = etlFiles;
    }




}


