package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * OrgMfr generated by hbm2java
 */
@Entity
@Table(name="org_mfr"
    , uniqueConstraints = @UniqueConstraint(columnNames="cds_mfr_id") 
)
public class OrgMfr  implements java.io.Serializable {


     private int orgId;
     private Org org;
     private String cdsMfrId;
     private Set<Product> products = new HashSet<Product>(0);
     private Set<PostSale> postSales = new HashSet<PostSale>(0);
     private Set<EtlSale> etlSales = new HashSet<EtlSale>(0);

    public OrgMfr() {
    }

	
    public OrgMfr(int orgId, Org org, String cdsMfrId) {
        this.orgId = orgId;
        this.org = org;
        this.cdsMfrId = cdsMfrId;
    }
    public OrgMfr(int orgId, Org org, String cdsMfrId, Set<Product> products, Set<PostSale> postSales, Set<EtlSale> etlSales) {
       this.orgId = orgId;
       this.org = org;
       this.cdsMfrId = cdsMfrId;
       this.products = products;
       this.postSales = postSales;
       this.etlSales = etlSales;
    }
   
     @Id 
    
    @Column(name="org_id", unique=true, nullable=false)
    public int getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(int orgId) {
        this.orgId = orgId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="org_id", unique=true, nullable=false, insertable=false, updatable=false)
    public Org getOrg() {
        return this.org;
    }
    
    public void setOrg(Org org) {
        this.org = org;
    }
    
    @Column(name="cds_mfr_id", unique=true, nullable=false, length=10)
    public String getCdsMfrId() {
        return this.cdsMfrId;
    }
    
    public void setCdsMfrId(String cdsMfrId) {
        this.cdsMfrId = cdsMfrId;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="orgMfr")
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="orgMfr")
    public Set<PostSale> getPostSales() {
        return this.postSales;
    }
    
    public void setPostSales(Set<PostSale> postSales) {
        this.postSales = postSales;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="orgMfr")
    public Set<EtlSale> getEtlSales() {
        return this.etlSales;
    }
    
    public void setEtlSales(Set<EtlSale> etlSales) {
        this.etlSales = etlSales;
    }




}


