package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProductSuspectHdr generated by hbm2java
 */
@Entity
@Table(name="product_suspect_hdr"
)
public class ProductSuspectHdr  implements java.io.Serializable {


     private int productSuspectHdrId;
     private String descr;

    public ProductSuspectHdr() {
    }

	
    public ProductSuspectHdr(int productSuspectHdrId) {
        this.productSuspectHdrId = productSuspectHdrId;
    }
    public ProductSuspectHdr(int productSuspectHdrId, String descr) {
       this.productSuspectHdrId = productSuspectHdrId;
       this.descr = descr;
    }
   
     @Id 
    
    @Column(name="product_suspect_hdr_id", unique=true, nullable=false)
    public int getProductSuspectHdrId() {
        return this.productSuspectHdrId;
    }
    
    public void setProductSuspectHdrId(int productSuspectHdrId) {
        this.productSuspectHdrId = productSuspectHdrId;
    }
    
    @Column(name="descr", length=60)
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }




}


