package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProductVw generated by hbm2java
 */
@Entity
@Table(name="product_vw"
)
public class ProductVw  implements java.io.Serializable {


     private ProductVwId id;

    public ProductVw() {
    }

    public ProductVw(ProductVwId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="orgCd", column=@Column(name="org_cd", length=16) ), 
        @AttributeOverride(name="orgNm", column=@Column(name="org_nm", length=32) ), 
        @AttributeOverride(name="productId", column=@Column(name="product_id") ), 
        @AttributeOverride(name="mfrId", column=@Column(name="mfr_id") ), 
        @AttributeOverride(name="productDescr", column=@Column(name="product_descr", length=60) ), 
        @AttributeOverride(name="mfrProductId", column=@Column(name="mfr_product_id", length=8) ), 
        @AttributeOverride(name="caseGtin", column=@Column(name="case_gtin", length=14) ), 
        @AttributeOverride(name="boxGtin", column=@Column(name="box_gtin", length=14) ), 
        @AttributeOverride(name="unitGtin", column=@Column(name="unit_gtin", length=14) ), 
        @AttributeOverride(name="unitsPerBox", column=@Column(name="units_per_box", precision=9, scale=0) ), 
        @AttributeOverride(name="unitsPerCase", column=@Column(name="units_per_case", precision=9, scale=0) ) } )
    public ProductVwId getId() {
        return this.id;
    }
    
    public void setId(ProductVwId id) {
        this.id = id;
    }




}


