package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductNomen generated by hbm2java
 */
@Entity
@Table(name="product_nomen"
)
public class ProductNomen  implements java.io.Serializable {


     private int productNomenId;
     private Org org;
     private Product product;
     private String productRefCd;
     private String caseGtin;
     private String descr;

    public ProductNomen() {
    }

	
    public ProductNomen(int productNomenId, Org org) {
        this.productNomenId = productNomenId;
        this.org = org;
    }
    public ProductNomen(int productNomenId, Org org, Product product, String productRefCd, String caseGtin, String descr) {
       this.productNomenId = productNomenId;
       this.org = org;
       this.product = product;
       this.productRefCd = productRefCd;
       this.caseGtin = caseGtin;
       this.descr = descr;
    }
   
     @Id 
    
    @Column(name="product_nomen_id", unique=true, nullable=false)
    public int getProductNomenId() {
        return this.productNomenId;
    }
    
    public void setProductNomenId(int productNomenId) {
        this.productNomenId = productNomenId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="org_id", nullable=false)
    public Org getOrg() {
        return this.org;
    }
    
    public void setOrg(Org org) {
        this.org = org;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id")
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    
    @Column(name="product_ref_cd", length=30)
    public String getProductRefCd() {
        return this.productRefCd;
    }
    
    public void setProductRefCd(String productRefCd) {
        this.productRefCd = productRefCd;
    }
    
    @Column(name="case_gtin", length=14)
    public String getCaseGtin() {
        return this.caseGtin;
    }
    
    public void setCaseGtin(String caseGtin) {
        this.caseGtin = caseGtin;
    }
    
    @Column(name="descr", length=60)
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }




}


