package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SaleProductCustVwId generated by hbm2java
 */
@Embeddable
public class SaleProductCustVwId  implements java.io.Serializable {


     private Integer etlSaleId;
     private Integer orgDistribId;
     private Integer orgMfrId;
     private Integer productId;
     private Integer distributorCustomerId;
     private BigDecimal invAmt;
     private BigDecimal caseEquivQty;
     private BigDecimal itemQty;
     private Date invDt;
     private String productDescr;

    public SaleProductCustVwId() {
    }

    public SaleProductCustVwId(Integer etlSaleId, Integer orgDistribId, Integer orgMfrId, Integer productId, Integer distributorCustomerId, BigDecimal invAmt, BigDecimal caseEquivQty, BigDecimal itemQty, Date invDt, String productDescr) {
       this.etlSaleId = etlSaleId;
       this.orgDistribId = orgDistribId;
       this.orgMfrId = orgMfrId;
       this.productId = productId;
       this.distributorCustomerId = distributorCustomerId;
       this.invAmt = invAmt;
       this.caseEquivQty = caseEquivQty;
       this.itemQty = itemQty;
       this.invDt = invDt;
       this.productDescr = productDescr;
    }
   

    @Column(name="etl_sale_id")
    public Integer getEtlSaleId() {
        return this.etlSaleId;
    }
    
    public void setEtlSaleId(Integer etlSaleId) {
        this.etlSaleId = etlSaleId;
    }

    @Column(name="org_distrib_id")
    public Integer getOrgDistribId() {
        return this.orgDistribId;
    }
    
    public void setOrgDistribId(Integer orgDistribId) {
        this.orgDistribId = orgDistribId;
    }

    @Column(name="org_mfr_id")
    public Integer getOrgMfrId() {
        return this.orgMfrId;
    }
    
    public void setOrgMfrId(Integer orgMfrId) {
        this.orgMfrId = orgMfrId;
    }

    @Column(name="product_id")
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    @Column(name="distributor_customer_id")
    public Integer getDistributorCustomerId() {
        return this.distributorCustomerId;
    }
    
    public void setDistributorCustomerId(Integer distributorCustomerId) {
        this.distributorCustomerId = distributorCustomerId;
    }

    @Column(name="inv_amt", precision=13, scale=5)
    public BigDecimal getInvAmt() {
        return this.invAmt;
    }
    
    public void setInvAmt(BigDecimal invAmt) {
        this.invAmt = invAmt;
    }

    @Column(name="case_equiv_qty", precision=13, scale=5)
    public BigDecimal getCaseEquivQty() {
        return this.caseEquivQty;
    }
    
    public void setCaseEquivQty(BigDecimal caseEquivQty) {
        this.caseEquivQty = caseEquivQty;
    }

    @Column(name="item_qty", precision=13, scale=5)
    public BigDecimal getItemQty() {
        return this.itemQty;
    }
    
    public void setItemQty(BigDecimal itemQty) {
        this.itemQty = itemQty;
    }

    @Column(name="inv_dt", length=13)
    public Date getInvDt() {
        return this.invDt;
    }
    
    public void setInvDt(Date invDt) {
        this.invDt = invDt;
    }

    @Column(name="product_descr", length=60)
    public String getProductDescr() {
        return this.productDescr;
    }
    
    public void setProductDescr(String productDescr) {
        this.productDescr = productDescr;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SaleProductCustVwId) ) return false;
		 SaleProductCustVwId castOther = ( SaleProductCustVwId ) other; 
         
		 return ( (this.getEtlSaleId()==castOther.getEtlSaleId()) || ( this.getEtlSaleId()!=null && castOther.getEtlSaleId()!=null && this.getEtlSaleId().equals(castOther.getEtlSaleId()) ) )
 && ( (this.getOrgDistribId()==castOther.getOrgDistribId()) || ( this.getOrgDistribId()!=null && castOther.getOrgDistribId()!=null && this.getOrgDistribId().equals(castOther.getOrgDistribId()) ) )
 && ( (this.getOrgMfrId()==castOther.getOrgMfrId()) || ( this.getOrgMfrId()!=null && castOther.getOrgMfrId()!=null && this.getOrgMfrId().equals(castOther.getOrgMfrId()) ) )
 && ( (this.getProductId()==castOther.getProductId()) || ( this.getProductId()!=null && castOther.getProductId()!=null && this.getProductId().equals(castOther.getProductId()) ) )
 && ( (this.getDistributorCustomerId()==castOther.getDistributorCustomerId()) || ( this.getDistributorCustomerId()!=null && castOther.getDistributorCustomerId()!=null && this.getDistributorCustomerId().equals(castOther.getDistributorCustomerId()) ) )
 && ( (this.getInvAmt()==castOther.getInvAmt()) || ( this.getInvAmt()!=null && castOther.getInvAmt()!=null && this.getInvAmt().equals(castOther.getInvAmt()) ) )
 && ( (this.getCaseEquivQty()==castOther.getCaseEquivQty()) || ( this.getCaseEquivQty()!=null && castOther.getCaseEquivQty()!=null && this.getCaseEquivQty().equals(castOther.getCaseEquivQty()) ) )
 && ( (this.getItemQty()==castOther.getItemQty()) || ( this.getItemQty()!=null && castOther.getItemQty()!=null && this.getItemQty().equals(castOther.getItemQty()) ) )
 && ( (this.getInvDt()==castOther.getInvDt()) || ( this.getInvDt()!=null && castOther.getInvDt()!=null && this.getInvDt().equals(castOther.getInvDt()) ) )
 && ( (this.getProductDescr()==castOther.getProductDescr()) || ( this.getProductDescr()!=null && castOther.getProductDescr()!=null && this.getProductDescr().equals(castOther.getProductDescr()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEtlSaleId() == null ? 0 : this.getEtlSaleId().hashCode() );
         result = 37 * result + ( getOrgDistribId() == null ? 0 : this.getOrgDistribId().hashCode() );
         result = 37 * result + ( getOrgMfrId() == null ? 0 : this.getOrgMfrId().hashCode() );
         result = 37 * result + ( getProductId() == null ? 0 : this.getProductId().hashCode() );
         result = 37 * result + ( getDistributorCustomerId() == null ? 0 : this.getDistributorCustomerId().hashCode() );
         result = 37 * result + ( getInvAmt() == null ? 0 : this.getInvAmt().hashCode() );
         result = 37 * result + ( getCaseEquivQty() == null ? 0 : this.getCaseEquivQty().hashCode() );
         result = 37 * result + ( getItemQty() == null ? 0 : this.getItemQty().hashCode() );
         result = 37 * result + ( getInvDt() == null ? 0 : this.getInvDt().hashCode() );
         result = 37 * result + ( getProductDescr() == null ? 0 : this.getProductDescr().hashCode() );
         return result;
   }   


}


