package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SaleProductCustVw generated by hbm2java
 */
@Entity
@Table(name="sale_product_cust_vw"
)
public class SaleProductCustVw  implements java.io.Serializable {


     private SaleProductCustVwId id;

    public SaleProductCustVw() {
    }

    public SaleProductCustVw(SaleProductCustVwId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="etlSaleId", column=@Column(name="etl_sale_id") ), 
        @AttributeOverride(name="orgDistribId", column=@Column(name="org_distrib_id") ), 
        @AttributeOverride(name="orgMfrId", column=@Column(name="org_mfr_id") ), 
        @AttributeOverride(name="productId", column=@Column(name="product_id") ), 
        @AttributeOverride(name="distributorCustomerId", column=@Column(name="distributor_customer_id") ), 
        @AttributeOverride(name="invAmt", column=@Column(name="inv_amt", precision=13, scale=5) ), 
        @AttributeOverride(name="caseEquivQty", column=@Column(name="case_equiv_qty", precision=13, scale=5) ), 
        @AttributeOverride(name="itemQty", column=@Column(name="item_qty", precision=13, scale=5) ), 
        @AttributeOverride(name="invDt", column=@Column(name="inv_dt", length=13) ), 
        @AttributeOverride(name="productDescr", column=@Column(name="product_descr", length=60) ) } )
    public SaleProductCustVwId getId() {
        return this.id;
    }
    
    public void setId(SaleProductCustVwId id) {
        this.id = id;
    }




}


