package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UtConditionRun generated by hbm2java
 */
@Entity
@Table(name="ut_condition_run"
)
public class UtConditionRun  implements java.io.Serializable {


     private int utConditionRunId;
     private Date startTs;
     private Set<UtConditionRunParm> utConditionRunParms = new HashSet<UtConditionRunParm>(0);
     private Set<UtConditionRunStep> utConditionRunSteps = new HashSet<UtConditionRunStep>(0);

    public UtConditionRun() {
    }

	
    public UtConditionRun(int utConditionRunId, Date startTs) {
        this.utConditionRunId = utConditionRunId;
        this.startTs = startTs;
    }
    public UtConditionRun(int utConditionRunId, Date startTs, Set<UtConditionRunParm> utConditionRunParms, Set<UtConditionRunStep> utConditionRunSteps) {
       this.utConditionRunId = utConditionRunId;
       this.startTs = startTs;
       this.utConditionRunParms = utConditionRunParms;
       this.utConditionRunSteps = utConditionRunSteps;
    }
   
     @Id 
    
    @Column(name="ut_condition_run_id", unique=true, nullable=false)
    public int getUtConditionRunId() {
        return this.utConditionRunId;
    }
    
    public void setUtConditionRunId(int utConditionRunId) {
        this.utConditionRunId = utConditionRunId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="start_ts", nullable=false, length=29)
    public Date getStartTs() {
        return this.startTs;
    }
    
    public void setStartTs(Date startTs) {
        this.startTs = startTs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="utConditionRun")
    public Set<UtConditionRunParm> getUtConditionRunParms() {
        return this.utConditionRunParms;
    }
    
    public void setUtConditionRunParms(Set<UtConditionRunParm> utConditionRunParms) {
        this.utConditionRunParms = utConditionRunParms;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="utConditionRun")
    public Set<UtConditionRunStep> getUtConditionRunSteps() {
        return this.utConditionRunSteps;
    }
    
    public void setUtConditionRunSteps(Set<UtConditionRunStep> utConditionRunSteps) {
        this.utConditionRunSteps = utConditionRunSteps;
    }




}


