package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UtConditionRunParmId generated by hbm2java
 */
@Embeddable
public class UtConditionRunParmId  implements java.io.Serializable {


     private int utConditionRunId;
     private String parmNm;

    public UtConditionRunParmId() {
    }

    public UtConditionRunParmId(int utConditionRunId, String parmNm) {
       this.utConditionRunId = utConditionRunId;
       this.parmNm = parmNm;
    }
   

    @Column(name="ut_condition_run_id", nullable=false)
    public int getUtConditionRunId() {
        return this.utConditionRunId;
    }
    
    public void setUtConditionRunId(int utConditionRunId) {
        this.utConditionRunId = utConditionRunId;
    }

    @Column(name="parm_nm", nullable=false, length=30)
    public String getParmNm() {
        return this.parmNm;
    }
    
    public void setParmNm(String parmNm) {
        this.parmNm = parmNm;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UtConditionRunParmId) ) return false;
		 UtConditionRunParmId castOther = ( UtConditionRunParmId ) other; 
         
		 return (this.getUtConditionRunId()==castOther.getUtConditionRunId())
 && ( (this.getParmNm()==castOther.getParmNm()) || ( this.getParmNm()!=null && castOther.getParmNm()!=null && this.getParmNm().equals(castOther.getParmNm()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUtConditionRunId();
         result = 37 * result + ( getParmNm() == null ? 0 : this.getParmNm().hashCode() );
         return result;
   }   


}


