package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UtCondition generated by hbm2java
 */
@Entity
@Table(name="ut_condition"
)
public class UtCondition  implements java.io.Serializable {


     private int utConditionId;
     private String conditionName;
     private String tableName;
     private String conditionMsg;
     private String sqlText;
     private String narrative;
     private Boolean conditionSeverity;
     private String conditionFormatStr;
     private String correctiveAction;
     private Set<UtConditionRunStep> utConditionRunSteps = new HashSet<UtConditionRunStep>(0);

    public UtCondition() {
    }

	
    public UtCondition(int utConditionId, String conditionName, String tableName, String sqlText) {
        this.utConditionId = utConditionId;
        this.conditionName = conditionName;
        this.tableName = tableName;
        this.sqlText = sqlText;
    }
    public UtCondition(int utConditionId, String conditionName, String tableName, String conditionMsg, String sqlText, String narrative, Boolean conditionSeverity, String conditionFormatStr, String correctiveAction, Set<UtConditionRunStep> utConditionRunSteps) {
       this.utConditionId = utConditionId;
       this.conditionName = conditionName;
       this.tableName = tableName;
       this.conditionMsg = conditionMsg;
       this.sqlText = sqlText;
       this.narrative = narrative;
       this.conditionSeverity = conditionSeverity;
       this.conditionFormatStr = conditionFormatStr;
       this.correctiveAction = correctiveAction;
       this.utConditionRunSteps = utConditionRunSteps;
    }
   
     @Id 
    
    @Column(name="ut_condition_id", unique=true, nullable=false)
    public int getUtConditionId() {
        return this.utConditionId;
    }
    
    public void setUtConditionId(int utConditionId) {
        this.utConditionId = utConditionId;
    }
    
    @Column(name="condition_name", nullable=false, length=30)
    public String getConditionName() {
        return this.conditionName;
    }
    
    public void setConditionName(String conditionName) {
        this.conditionName = conditionName;
    }
    
    @Column(name="table_name", nullable=false, length=60)
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    
    @Column(name="condition_msg")
    public String getConditionMsg() {
        return this.conditionMsg;
    }
    
    public void setConditionMsg(String conditionMsg) {
        this.conditionMsg = conditionMsg;
    }
    
    @Column(name="sql_text", nullable=false)
    public String getSqlText() {
        return this.sqlText;
    }
    
    public void setSqlText(String sqlText) {
        this.sqlText = sqlText;
    }
    
    @Column(name="narrative")
    public String getNarrative() {
        return this.narrative;
    }
    
    public void setNarrative(String narrative) {
        this.narrative = narrative;
    }
    
    @Column(name="condition_severity", precision=1, scale=0)
    public Boolean getConditionSeverity() {
        return this.conditionSeverity;
    }
    
    public void setConditionSeverity(Boolean conditionSeverity) {
        this.conditionSeverity = conditionSeverity;
    }
    
    @Column(name="condition_format_str")
    public String getConditionFormatStr() {
        return this.conditionFormatStr;
    }
    
    public void setConditionFormatStr(String conditionFormatStr) {
        this.conditionFormatStr = conditionFormatStr;
    }
    
    @Column(name="corrective_action")
    public String getCorrectiveAction() {
        return this.correctiveAction;
    }
    
    public void setCorrectiveAction(String correctiveAction) {
        this.correctiveAction = correctiveAction;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="utCondition")
    public Set<UtConditionRunStep> getUtConditionRunSteps() {
        return this.utConditionRunSteps;
    }
    
    public void setUtConditionRunSteps(Set<UtConditionRunStep> utConditionRunSteps) {
        this.utConditionRunSteps = utConditionRunSteps;
    }




}


