package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UtConditionRowMsg generated by hbm2java
 */
@Entity
@Table(name="ut_condition_row_msg"
)
public class UtConditionRowMsg  implements java.io.Serializable {


     private UtConditionRowMsgId id;
     private UtConditionRunStep utConditionRunStep;
     private String conditionMsg;

    public UtConditionRowMsg() {
    }

	
    public UtConditionRowMsg(UtConditionRowMsgId id, UtConditionRunStep utConditionRunStep) {
        this.id = id;
        this.utConditionRunStep = utConditionRunStep;
    }
    public UtConditionRowMsg(UtConditionRowMsgId id, UtConditionRunStep utConditionRunStep, String conditionMsg) {
       this.id = id;
       this.utConditionRunStep = utConditionRunStep;
       this.conditionMsg = conditionMsg;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="utConditionRunStepId", column=@Column(name="ut_condition_run_step_id", nullable=false) ), 
        @AttributeOverride(name="tablePk", column=@Column(name="table_pk", nullable=false) ) } )
    public UtConditionRowMsgId getId() {
        return this.id;
    }
    
    public void setId(UtConditionRowMsgId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ut_condition_run_step_id", nullable=false, insertable=false, updatable=false)
    public UtConditionRunStep getUtConditionRunStep() {
        return this.utConditionRunStep;
    }
    
    public void setUtConditionRunStep(UtConditionRunStep utConditionRunStep) {
        this.utConditionRunStep = utConditionRunStep;
    }
    
    @Column(name="condition_msg", length=200)
    public String getConditionMsg() {
        return this.conditionMsg;
    }
    
    public void setConditionMsg(String conditionMsg) {
        this.conditionMsg = conditionMsg;
    }




}


