package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UtConditionRunParm generated by hbm2java
 */
@Entity
@Table(name="ut_condition_run_parm"
)
public class UtConditionRunParm  implements java.io.Serializable {


     private UtConditionRunParmId id;
     private UtConditionRun utConditionRun;
     private String parmType;
     private String parmValueStr;

    public UtConditionRunParm() {
    }

	
    public UtConditionRunParm(UtConditionRunParmId id, UtConditionRun utConditionRun, String parmType) {
        this.id = id;
        this.utConditionRun = utConditionRun;
        this.parmType = parmType;
    }
    public UtConditionRunParm(UtConditionRunParmId id, UtConditionRun utConditionRun, String parmType, String parmValueStr) {
       this.id = id;
       this.utConditionRun = utConditionRun;
       this.parmType = parmType;
       this.parmValueStr = parmValueStr;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="utConditionRunId", column=@Column(name="ut_condition_run_id", nullable=false) ), 
        @AttributeOverride(name="parmNm", column=@Column(name="parm_nm", nullable=false, length=30) ) } )
    public UtConditionRunParmId getId() {
        return this.id;
    }
    
    public void setId(UtConditionRunParmId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ut_condition_run_id", nullable=false, insertable=false, updatable=false)
    public UtConditionRun getUtConditionRun() {
        return this.utConditionRun;
    }
    
    public void setUtConditionRun(UtConditionRun utConditionRun) {
        this.utConditionRun = utConditionRun;
    }
    
    @Column(name="parm_type", nullable=false, length=30)
    public String getParmType() {
        return this.parmType;
    }
    
    public void setParmType(String parmType) {
        this.parmType = parmType;
    }
    
    @Column(name="parm_value_str", length=30)
    public String getParmValueStr() {
        return this.parmValueStr;
    }
    
    public void setParmValueStr(String parmValueStr) {
        this.parmValueStr = parmValueStr;
    }




}


