package com.pds.pdssr.models;
// Generated Jul 5, 2018 11:41:30 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ValidatedAddress generated by hbm2java
 */
@Entity
@Table(name="validated_address"
)
public class ValidatedAddress  implements java.io.Serializable {


     private int validatedAddressId;
     private String addr1;
     private String addr2;
     private String city;
     private String state;
     private String postalCd;
     private String validAddr1;
     private String validAddr2;
     private String validCity;
     private String validState;
     private String validPostalCd;
     private String validationMsg;

    public ValidatedAddress() {
    }

	
    public ValidatedAddress(int validatedAddressId) {
        this.validatedAddressId = validatedAddressId;
    }
    public ValidatedAddress(int validatedAddressId, String addr1, String addr2, String city, String state, String postalCd, String validAddr1, String validAddr2, String validCity, String validState, String validPostalCd, String validationMsg) {
       this.validatedAddressId = validatedAddressId;
       this.addr1 = addr1;
       this.addr2 = addr2;
       this.city = city;
       this.state = state;
       this.postalCd = postalCd;
       this.validAddr1 = validAddr1;
       this.validAddr2 = validAddr2;
       this.validCity = validCity;
       this.validState = validState;
       this.validPostalCd = validPostalCd;
       this.validationMsg = validationMsg;
    }
   
     @Id 
    
    @Column(name="validated_address_id", unique=true, nullable=false)
    public int getValidatedAddressId() {
        return this.validatedAddressId;
    }
    
    public void setValidatedAddressId(int validatedAddressId) {
        this.validatedAddressId = validatedAddressId;
    }
    
    @Column(name="addr_1", length=30)
    public String getAddr1() {
        return this.addr1;
    }
    
    public void setAddr1(String addr1) {
        this.addr1 = addr1;
    }
    
    @Column(name="addr_2", length=30)
    public String getAddr2() {
        return this.addr2;
    }
    
    public void setAddr2(String addr2) {
        this.addr2 = addr2;
    }
    
    @Column(name="city", length=25)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    
    @Column(name="state", length=2)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    
    @Column(name="postal_cd", length=9)
    public String getPostalCd() {
        return this.postalCd;
    }
    
    public void setPostalCd(String postalCd) {
        this.postalCd = postalCd;
    }
    
    @Column(name="valid_addr_1", length=30)
    public String getValidAddr1() {
        return this.validAddr1;
    }
    
    public void setValidAddr1(String validAddr1) {
        this.validAddr1 = validAddr1;
    }
    
    @Column(name="valid_addr_2", length=30)
    public String getValidAddr2() {
        return this.validAddr2;
    }
    
    public void setValidAddr2(String validAddr2) {
        this.validAddr2 = validAddr2;
    }
    
    @Column(name="valid_city", length=25)
    public String getValidCity() {
        return this.validCity;
    }
    
    public void setValidCity(String validCity) {
        this.validCity = validCity;
    }
    
    @Column(name="valid_state", length=2)
    public String getValidState() {
        return this.validState;
    }
    
    public void setValidState(String validState) {
        this.validState = validState;
    }
    
    @Column(name="valid_postal_cd", length=9)
    public String getValidPostalCd() {
        return this.validPostalCd;
    }
    
    public void setValidPostalCd(String validPostalCd) {
        this.validPostalCd = validPostalCd;
    }
    
    @Column(name="validation_msg", length=200)
    public String getValidationMsg() {
        return this.validationMsg;
    }
    
    public void setValidationMsg(String validationMsg) {
        this.validationMsg = validationMsg;
    }




}


